# Generated by Django 5.2.3 on 2025-07-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="Employee",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="name",
            new_name="lastname",
        ),
    ]
