# Generated by Django 5.2.3 on 2025-07-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0002_rename_person_employee_rename_name_employee_lastname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="lastname",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="field",
            new_name="job_title",
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
